### ISSUE TITLE
Koios backend response was unsuccessful

### ISSUE THREAD

**Issue by besiwims** [CardanoSharp/cscli#12]
I do not know why it was unsuccessful and I do not know what to do

**Comment by nothingalike** [comment]
> I do not know why it was unsuccessful and I do not know what to do

sorry for the delay. the issues are being worked on

**Comment by safestak-keith** [comment]
Fixed with https://github.com/cardano-community/cardanosharp-koios/pull/19 and new package released at https://www.nuget.org/packages/CardanoSharp.Koios.Client/1.0.8
