### ISSUE TITLE
Add On-Chain Querying

### ISSUE THREAD

**Issue by nothingalike** [CardanoSharp/cscli#2]
Thinking we could add the Koios SDK to get things like Protocol Parameters

**Comment by safestak-keith** [comment]
Yeah I imagined cscli to be a _light_ cardano-cli with advanced wallet commands. We can start with the protocol params and eventually work our way to querying the tip, the UTxOs from address(es), to ultimately building and submitting Tx. Do you want to start on the protocol params bit?
